routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth','prefix' => 'admin'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('news','NewsController');


        Route::group(['middleware' => ['permission:view-project-category|project-category-modification|add-new-project-category']], function () {
            Route::resource('projects/categories','ProjectCategoryController',['as' => 'projects']);
        });
        Route::group(['middleware' => ['permission:view-project|project-modification|add-new-project']], function () {
            Route::resource('projects','ProjectController');
        });

        Route::group(['middleware' => ['permission:view-career|career-modification|add-new-career']], function () {
            Route::resource('careers','CareerController');
        });

        Route::group(['middleware' => ['permission:view-page-image|page-image-modification']], function () {
            Route::get('settings/page-image',['uses' => 'PageImageController@index','as' => 'settings.page-image.index']);
            Route::post('settings/page-image',['uses' => 'PageImageController@update','as' => 'settings.page-image.update']);
        });

        Route::group(['middleware' => ['permission:view-seo|seo-modification']], function () {
            Route::get('settings/seo',['uses' => 'SeoController@index','as' => 'settings.seo.index']);
            Route::post('settings/seo',['uses' => 'SeoController@update','as' => 'settings.seo.update']);
        });
        Route::group(['middleware' => ['permission:view-social-media|social-media-modification']], function () {
            Route::get('settings/social-media',['uses' => 'SocialMediaController@index','as' => 'settings.social-media.index']);
            Route::post('settings/social-media',['uses' => 'SocialMediaController@update','as' => 'settings.social-media.update']);
        });

        Route::prefix('who-are-we')->group(function(){
            Route::group(['middleware' => ['permission:company-profile']], function () {
                Route::get('/',['uses' => 'WhoAreWeController@index','as' => 'whoAreWe.index']);
                Route::patch('updateProfile',['uses' => 'WhoAreWeController@updateProfile','as' => 'whoAreWe.updateProfile']);
            });

            Route::group(['middleware' => ['permission:management-team']], function () {
                Route::post('save-management-team','WhoAreWeController@saveManagementTeam');
                Route::post('update-management-team/{id}','WhoAreWeController@updateManagementTeam');
                Route::get('get-management-team','WhoAreWeController@getManagementTeam');
                Route::delete('remove-management-team/{id}','WhoAreWeController@removeManagementTeam');
            });

            Route::group(['middleware' => ['permission:chairman-message']], function () {
                Route::patch('update-message-from-ceo',['uses' => 'WhoAreWeController@update_message','as' => 'whoAreWe.updateMessage']);
            });
        });

        Route::group(['middleware' => ['permission:banner-slider|our-story|video']], function () {
            Route::get('home-page',['uses' => 'HomePageController@index','as' => 'homePage.index']);
            Route::get('home-page/get-slider',['uses' => 'HomePageController@getSlider','as' => 'homePage.getSlider']);
            Route::post('home-page/save-sliders',[ 'uses' => 'HomePageController@saveSlider' ,'as' => 'homePage.saveSlider']);
            Route::post('home-page/remove-file','HomePageController@removeFile');
            Route::post('home-page/discover-story',['uses' => 'HomePageController@saveDiscoverStory','as' => 'homePage.discoverStory']);
            Route::post('home-page/video',['uses' => 'HomePageController@saveVideoKey','as' => 'homePage.saveVideoKey']);
        });

        Route::group(['middleware' => ['permission:contact-us-page']], function () {
            Route::get('contact-us',['uses' => 'ContactUsController@index','as' => 'contactUs.index']);
            Route::patch('contact-us',['uses' => 'ContactUsController@update', 'as' => 'contactUs.update']);
        });

        Route::group(['middleware' => ['permission:about-us-page']], function () {
            Route::prefix('about-us')->group(function(){
                Route::get('/',['uses' => 'AboutUsController@index','as' => 'aboutUs.index']);
                Route::patch('/',['uses' => 'AboutUsController@update','as' => 'aboutUs.update']);
                Route::patch('update-header-image',['uses' => 'AboutUsController@updateHeaderImage','as' => 'aboutUs.updateHeaderImage']);
                Route::patch('update-company-description',['uses' => 'AboutUsController@updateCompanyDescription','as' => 'aboutUs.updateCompanyDescription']);
                Route::patch('update-company-profile',['uses' => 'AboutUsController@updateCompanyProfile','as' => 'aboutUs.updateCompanyProfile']);
            });
        });

        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('upload-image','ImageController@uploadImage');
        Route::post('upload-temp-multiple',['as' => 'dropzonesSaveMultiple', 'uses' => 'ImageController@uploadTempMultiple']);
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
    });  
});

Route::group(['namespace' => 'Client','as' =>'client.'],function(){
    Route::get('/',['uses' => 'FrontendController@index','as' => 'homepage']);
    Route::get('/who-we-are',['uses' => 'FrontendController@whoWeAre','as' => 'who-we-are']);
    Route::get('/about-us',['uses' => 'FrontendController@aboutUs','as' => 'about-us']);
    Route::get('/our-projects',['uses' => 'FrontendController@ourProjects','as' => 'our-projects']);
    Route::get('/our-projects/{category}',['uses' => 'FrontendController@projectCategory','as' => 'project-category']);
    Route::get('/contact',['uses' => 'FrontendController@contact','as' => 'contact']);
    Route::get('/career-opportunities',['uses' => 'FrontendController@career','as' => 'career-opportunities']);
    Route::get('/career-opportunities/{id}',['uses' => 'FrontendController@careerDetail','as' => 'career-detail']);
    Route::get('/news/{id}',['uses' => 'FrontendController@newsDetail', 'as' => 'news-detail']);
    Route::get('/news',['uses' => 'FrontendController@news', 'as' => 'news']);
});

app/Http/Controllers/Admin/ProjectController.php
<?php

namespace App\Http\Controllers\Admin;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Model\Project;
use App\Model\ProjectCategory;
use DB;

class ProjectController extends Controller
{
    public function index(){
        $projects = Project::with('category')->orderBy('id','DESC')->paginate(15);
        //  dd($projects);  
        return view('admin.project.index',compact('projects'));
    }

    public function create()
    {
        $categories = ['0' => 'Choose Category'] + ProjectCategory::pluck('name','id')->toArray();
        return view('admin.project.add-update',compact('categories'));
    }

    public function store(Request $request)
    {
        $this->validate($request,[
            'name' => 'required|unique:users,name',
            'description' => 'required'
        ]);
        
        $this->saveToDB($request->all());
        return redirect()->route('projects.index')->withSuccess('You have just added a category successfully!');
    }

    public function edit($id)
    {
        $project = Project::findOrFail($id);
        $categories = ['0' => 'Choose Category'] + ProjectCategory::pluck('name','id')->toArray();
        return view('admin.project.add-update',compact('project','categories'));
    }

    public function update(Request $request, $id)
    {
        $this->validate($request,[
            'name' => 'required|unique:users,name,'.$id,
            'description' => 'required'
        ]);

        $this->saveToDB($request->all(),$id);
        return redirect()->route('projects.index')->withSuccess('You have just updated a category successfully!');
    }

    public function destroy($id)
    {
        $result = false;
        $project = Project::find($id);
        if($project){
            DB::beginTransaction();
            try{
                if($project->delete()){
                    $result = true;
                }
                DB::commit();
            }catch(Exception $exception){
                DB::rollback();
                $result = false;
            }
        }
        return response()->json(['success' => $result]);
    }

    public function saveToDB($data, $id=null){
        DB::beginTransaction();
        try{
            $project = isset($id) ? Project::find($id) : new Project;
            if(!$project) return redirect()->back()->withError('There is no record found!');

            $project->fill($data);
            if($project->save()){
                if(isset($data['image']) && !empty($data['image'])){
                    $project->clearMediaCollection('images'); 
                    $project->addMedia($data['image'])
                         ->toMediaCollection('images');
                }
            }

            DB::commit();
        }catch(Exception $ex){
            DB::rollback();
            return redirect()->back()->withError('There was an error during operation!');
        }
        return $project;
    }
}

resources/views/admin/project/category/add-update.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">{{ isset($category) ? 'Update' : 'Add' }} Project Category</h4>
            </div>

            @if(isset($category))
            {{ Form::model($category,['route' => ['projects.categories.update',$category->id], 'method' => 'PUT']) }}
            @else
            {{ Form::open(['route' => 'projects.categories.store', 'method' => 'POST']) }}
            @endif
            @csrf
            <div class="card-content">
                <div class="card-body">
                    <div class="row">
                        <div class="col-md-6">
                            <fieldset class="form-group">
                                <label for="basicInput">Category Name</label>
                                {!! Form::text('name',null,['class' => 'form-control', 'placeholder' => 'Enter category name']) !!}
                                @component('common.error_helper_text',['key' => "name"])@endcomponent
                            </fieldset>
                        </div>
                    </div>
                </div>
                <div class="card-footer">
                    <a href="{{route('projects.categories.index')}}" class="btn grey btn-outline-secondary">Discard</a>
                    <button type="submit" class="btn btn-outline-primary">Save changes</button>
                </div>
            </div>
            {{ Form::close() }}
        </div>
    </div>
</div>
@endsection

resources/views/admin/project/category/index.blade.php
@extends('admin.layouts.master')

@section('content')
<div class="row">
    <div class="col-md-12">            
        <div class="card">
            <div class="card-header">
                <h4 class="card-title">Project Categories</h4>
                @can('add-new-project-category')
                <div class="heading-elements">
                    <a href="{{route('projects.categories.create')}}" class="btn btn-sm btn-icon btn-success">
                        <i class="ft-plus white"></i> Add New
                    </a>
                </div>
                @endcan
            </div>
            <div class="card-content">
                <div class="card-body">
                    @include('admin.includes.success-msg')
                    @include('admin.includes.error-msg')
                    <div class="table-responsive">
                        <table class="table table-bordered">
                            <thead class="thead-light">
                                <th>#</th>
                                <th>Name</th>
                                <th>Number of Projects</th>
                                <th>Action</th>
                            </thead>
                            <tbody>
                                <tr>
                                    @if(isset($categories) && $categories->count() > 0) 
                                        @foreach($categories as $key => $row)
                                        <tr>
                                            <td>{{($categories->perPage() * ($categories->currentPage() - 1)) + $key + 1}}</td>
                                            <td>{{ $row->name }}</td>
                                            <td>{{ $row->projects->count() }}</td>
                                            <td class="group-btn-action">
                                                @canany(['project-category-modification'])
                                                    <div class="btn-group btn-group-sm" role="group" aria-label="Basic example">
                                                        <a href="{{ route('projects.categories.edit',$row->id) }}" class="btn btn-outline-warning"><i class="ft-edit-3"></i> Edit</a>
                                                        <button type="button" class="btn btn-outline-danger delete" data-route="{{route('projects.categories.destroy',$row->id)}}"><i class="ft-trash-2"></i> Delete</button>
                                                    </div>
                                                @endcanany
                                            </td>
                                        </tr>
                                        @endforeach
                                    @else 
                                        <tr><td colspan="4">No Data</td></tr>
                                    @endif
                                </tr>
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
            @if(isset($categories) && $categories->count() > 0)
            <div class="card-footer">
                @if($categories->hasMorePages())
                    <div class="mb-2">
                        {!! $categories->appends(Input::except('page'))->render() !!}
                    </div>
                @endif
                <div>
                    Showing {{$categories->firstItem()}} to {{$categories->lastItem()}}
                    of  {{$categories->total()}} entries
                </div>
            </div>
            @endif
        </div>
    </div>
</div>
@endsection