routes/web.php
<?php

Route::namespace('Admin')->group(function(){
    Route::namespace('Auth')->group(function(){
        Route::get('/login', ['uses' => 'LoginController@showLoginForm', 'as' => 'login']);
        Route::post('/login', ['uses' => 'LoginController@login', 'as' => 'postLogin']);
        Route::post('/logout', ['uses' => 'LoginController@logout', 'as' => 'logout']);
    });
    
    Route::group(['middleware' => 'auth','prefix' => 'admin'], function(){
        Route::get('/dashboard',['uses' => 'DashboardController@index', 'as' => 'dashboard']);

        Route::group(['middleware' => ['permission:view-user|user-modification|add-new-user']], function () {
            Route::resource('/users','UserController');
        });
        Route::group(['middleware' => ['permission:view-role|role-modification|add-new-role']], function () {
            Route::resource('/roles','UserRoleController');
        });
        Route::resource('news','NewsController');


        Route::group(['middleware' => ['permission:view-project-category|project-category-modification|add-new-project-category']], function () {
            Route::resource('projects/categories','ProjectCategoryController',['as' => 'projects']);
        });
        Route::group(['middleware' => ['permission:view-project|project-modification|add-new-project']], function () {
            Route::resource('projects','ProjectController');
        });

        Route::group(['middleware' => ['permission:view-career|career-modification|add-new-career']], function () {
            Route::resource('careers','CareerController');
        });

        Route::group(['middleware' => ['permission:view-page-image|page-image-modification']], function () {
            Route::get('settings/page-image',['uses' => 'PageImageController@index','as' => 'settings.page-image.index']);
            Route::post('settings/page-image',['uses' => 'PageImageController@update','as' => 'settings.page-image.update']);
        });

        Route::group(['middleware' => ['permission:view-seo|seo-modification']], function () {
            Route::get('settings/seo',['uses' => 'SeoController@index','as' => 'settings.seo.index']);
            Route::post('settings/seo',['uses' => 'SeoController@update','as' => 'settings.seo.update']);
        });
        Route::group(['middleware' => ['permission:view-social-media|social-media-modification']], function () {
            Route::get('settings/social-media',['uses' => 'SocialMediaController@index','as' => 'settings.social-media.index']);
            Route::post('settings/social-media',['uses' => 'SocialMediaController@update','as' => 'settings.social-media.update']);
        });

        Route::prefix('who-are-we')->group(function(){
            Route::group(['middleware' => ['permission:company-profile']], function () {
                Route::get('/',['uses' => 'WhoAreWeController@index','as' => 'whoAreWe.index']);
                Route::patch('updateProfile',['uses' => 'WhoAreWeController@updateProfile','as' => 'whoAreWe.updateProfile']);
            });

            Route::group(['middleware' => ['permission:management-team']], function () {
                Route::post('save-management-team','WhoAreWeController@saveManagementTeam');
                Route::post('update-management-team/{id}','WhoAreWeController@updateManagementTeam');
                Route::get('get-management-team','WhoAreWeController@getManagementTeam');
                Route::delete('remove-management-team/{id}','WhoAreWeController@removeManagementTeam');
            });

            Route::group(['middleware' => ['permission:chairman-message']], function () {
                Route::patch('update-message-from-ceo',['uses' => 'WhoAreWeController@update_message','as' => 'whoAreWe.updateMessage']);
            });
        });

        Route::group(['middleware' => ['permission:banner-slider|our-story|video']], function () {
            Route::get('home-page',['uses' => 'HomePageController@index','as' => 'homePage.index']);
            Route::get('home-page/get-slider',['uses' => 'HomePageController@getSlider','as' => 'homePage.getSlider']);
            Route::post('home-page/save-sliders',[ 'uses' => 'HomePageController@saveSlider' ,'as' => 'homePage.saveSlider']);
            Route::post('home-page/remove-file','HomePageController@removeFile');
            Route::post('home-page/discover-story',['uses' => 'HomePageController@saveDiscoverStory','as' => 'homePage.discoverStory']);
            Route::post('home-page/video',['uses' => 'HomePageController@saveVideoKey','as' => 'homePage.saveVideoKey']);
        });

        Route::group(['middleware' => ['permission:contact-us-page']], function () {
            Route::get('contact-us',['uses' => 'ContactUsController@index','as' => 'contactUs.index']);
            Route::patch('contact-us',['uses' => 'ContactUsController@update', 'as' => 'contactUs.update']);
        });

        Route::group(['middleware' => ['permission:about-us-page']], function () {
            Route::prefix('about-us')->group(function(){
                Route::get('/',['uses' => 'AboutUsController@index','as' => 'aboutUs.index']);
                Route::patch('/',['uses' => 'AboutUsController@update','as' => 'aboutUs.update']);
                Route::patch('update-header-image',['uses' => 'AboutUsController@updateHeaderImage','as' => 'aboutUs.updateHeaderImage']);
                Route::patch('update-company-description',['uses' => 'AboutUsController@updateCompanyDescription','as' => 'aboutUs.updateCompanyDescription']);
                Route::patch('update-company-profile',['uses' => 'AboutUsController@updateCompanyProfile','as' => 'aboutUs.updateCompanyProfile']);
            });
        });

        Route::resource('/users/profile','EditProfileController',['as' => 'users']);

        //ajax upload image
        Route::post('upload-image','ImageController@uploadImage');
        Route::post('upload-temp-multiple',['as' => 'dropzonesSaveMultiple', 'uses' => 'ImageController@uploadTempMultiple']);
        Route::post('/save-temp-image', ['as' => 'dropzoneSaveTempImage', 'uses' => 'ImageController@dropzoneSaveTempImage']);
    });  
});

Route::group(['namespace' => 'Client','as' =>'client.'],function(){
    Route::get('/',['uses' => 'FrontendController@index','as' => 'homepage']);
    Route::get('/who-we-are',['uses' => 'FrontendController@whoWeAre','as' => 'who-we-are']);
    Route::get('/about-us',['uses' => 'FrontendController@aboutUs','as' => 'about-us']);
    Route::get('/our-projects',['uses' => 'FrontendController@ourProjects','as' => 'our-projects']);
    Route::get('/our-projects/{category}',['uses' => 'FrontendController@projectCategory','as' => 'project-category']);
    Route::get('/contact',['uses' => 'FrontendController@contact','as' => 'contact']);
    Route::get('/career-opportunities',['uses' => 'FrontendController@career','as' => 'career-opportunities']);
    Route::get('/career-opportunities/{id}',['uses' => 'FrontendController@careerDetail','as' => 'career-detail']);
    Route::get('/news/{id}',['uses' => 'FrontendController@newsDetail', 'as' => 'news-detail']);
    Route::get('/news',['uses' => 'FrontendController@news', 'as' => 'news']);
});

resources/views/admin/layouts/head.blade.php
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=0, minimal-ui">
<meta name="description" content="Stack admin is super flexible, powerful, clean &amp; modern responsive bootstrap 4 admin template with unlimited possibilities.">
<meta name="keywords" content="admin template, stack admin template, dashboard template, flat admin template, responsive admin template, web app">
<meta name="author" content="PIXINVENT">
<title>Admin - Big Biz</title>
<link rel="apple-touch-icon" href="/client/images/BigBiz.png">
<link rel="shortcut icon" href="/client/images/BigBiz.png">
<meta name="csrf-token" content="{{ csrf_token() }}" />
<link href="https://fonts.googleapis.com/css?family=Montserrat:300,300i,400,400i,500,500i%7COpen+Sans:300,300i,400,400i,600,600i,700,700i" rel="stylesheet">

<!-- BEGIN: Vendor CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/vendors.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/extensions/unslider.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/weather-icons/climacons.min.css">
<link rel="stylesheet" type="text/css" href="/app-assets/fonts/meteocons/style.css">
<link rel="stylesheet" type="text/css" href="/app-assets/vendors/css/charts/morris.css">
<!-- END: Vendor CSS-->

<!-- BEGIN: Theme CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/bootstrap-extended.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/colors.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/components.css">
<!-- END: Theme CSS-->

<!-- BEGIN: Page CSS-->
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu-modern.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/menu/menu-types/vertical-menu.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="/app-assets/fonts/simple-line-icons/style.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/core/colors/palette-gradient.css">
<link rel="stylesheet" type="text/css" href="/app-assets/css/pages/timeline.css">
<!-- END: Page CSS-->

<link rel="stylesheet" type="text/css" href="/app-assets/custom/css/custom.css">

@yield('page-css')
@yield('custom-css')

resources/views/admin/layouts/header.blade.php
<nav class="header-navbar navbar-expand-md navbar navbar-with-menu fixed-top navbar-semi-light bg-gradient-x-grey-blue">
    <div class="navbar-wrapper">
        <div class="navbar-header">
            <ul class="nav navbar-nav flex-row">
                <li class="nav-item mobile-menu d-md-none mr-auto"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu font-large-1"></i></a></li>
                <li class="nav-item"><a class="navbar-brand" href=""><img class="brand-logo" alt="stack admin logo" src="/app-assets/images/logo/stack-logo.png">
                        <h2 class="brand-text">BigBiz</h2>
                    </a></li>
                <li class="nav-item d-md-none"><a class="nav-link open-navbar-container" data-toggle="collapse" data-target="#navbar-mobile"><i class="fa fa-ellipsis-v"></i></a></li>
            </ul>
        </div>
        <div class="navbar-container content">
            <div class="collapse navbar-collapse" id="navbar-mobile">
                <ul class="nav navbar-nav mr-auto float-left">
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-menu-main menu-toggle hidden-xs" href="#"><i class="ft-menu"></i></a></li>
                    <li class="nav-item d-none d-md-block"><a class="nav-link nav-link-expand" href="#"><i class="ficon ft-maximize"></i></a></li>
                </ul>
                <ul class="nav navbar-nav float-right">
                    @php $auth = auth()->user(); $image = $auth->getFirstMedia('images'); @endphp
                    <li class="dropdown dropdown-user nav-item">
                        <a class="dropdown-toggle nav-link dropdown-user-link" href="#" data-toggle="dropdown">
                            <span class="avatar avatar-online"><img class="rounded-circle" src="{{ $image ? $image->getUrl() : ''}}" alt="{{$auth->name}}"><i></i></span>
                            <span class="user-name">{{ $auth ? $auth->name : 'Big Biz' }}</span></a>
                        <div class="dropdown-menu dropdown-menu-right">
                            <a class="dropdown-item" href="{{route('users.profile.edit',$auth->id)}}"><i class="ft-user"></i> Edit Profile</a>
                            <a class="dropdown-item" href="#" onclick="event.preventDefault(); document.getElementById('frm-logout').submit();"><i class="ft-power"></i> Logout</a>
                            <form id="frm-logout" action="{{route('logout')}}" method="POST" style="display: none;">
                                {{ csrf_field() }}
                            </form>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

resources/views/admin/layouts/master.blade.php
<!DOCTYPE html>
<html class="loading" lang="en" data-textdirection="ltr">
<head>
    @include('admin.layouts.head')
    @yield('page-style')
    @yield('dropzone-css')
</head>
<body class="vertical-layout vertical-menu 2-columns   fixed-navbar" data-open="click" data-menu="vertical-menu" data-col="2-columns">
    @include('admin.layouts.header')
    @include('admin.layouts.sidebar')
    <div class="app-content content">
        <div class="content-wrapper">
            <div class="content-header row">
            </div>
            <div class="content-body">
                @yield('content')
            </div>
        </div>
    </div>
    <div class="sidenav-overlay"></div>
    <div class="drag-target"></div>
    <footer class="footer footer-static footer-dark navbar-border">
        <p class="clearfix blue-grey lighten-2 text-sm-center mb-0 px-2"><span class="float-md-left d-block d-md-inline-block">Copyright &copy; {{date('Y')}} <a href="/" class="text-bold-800 grey darken-2" target="_blank">BIGBIZ </a></span><span class="float-md-right d-none d-lg-block">Powered By <a class="text-bold-800 grey darken-2" href="https://www.mkoratec.com" target="_blank">MKORATEC </a></span></p>
    </footer>
    @include('admin.layouts.script')
    @yield('dropzone-script')
    @yield('page-script')
</body>
</html>

resources/views/admin/layouts/script.blade.php
<!-- BEGIN: Vendor JS-->
<script src="/app-assets/vendors/js/vendors.min.js"></script>
<!-- BEGIN Vendor JS-->

<!-- BEGIN: Page Vendor JS-->
<script src="/app-assets/vendors/js/charts/raphael-min.js"></script>
<script src="/app-assets/vendors/js/charts/morris.min.js"></script>
<script src="/app-assets/vendors/js/extensions/unslider-min.js"></script>
<script src="/app-assets/vendors/js/timeline/horizontal-timeline.js"></script>
<script src="/app-assets/vendors/js/forms/icheck/icheck.min.js"></script>
<script src="/app-assets/vendors/js/extensions/sweetalert.min.js"></script>
<!-- END: Page Vendor JS-->

<!-- BEGIN: Theme JS-->
<script src="/app-assets/js/core/app-menu.js"></script>
<script src="/app-assets/js/core/app.js"></script>
<!-- END: Theme JS-->
<script src="/app-assets/vendors/js/extensions/sweetalert.min.js"></script>
<!-- BEGIN: Page JS-->
<script src="/app-assets/js/scripts/pages/dashboard-ecommerce.js"></script>
<script src="/app-assets/js/scripts/extensions/sweet-alerts.js"></script>
<script type="text/javascript">
    $.ajaxSetup({
        headers: {
            'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
        }
    });
</script>
<script>
    $(".nav-item a").each(function() {
    if ((window.location.href.indexOf($(this).attr('href'))) > -1) {
        $(this).parent().addClass('active');
    }
});
</script>
<!-- END: Page JS-->
<script src="/app-assets/custom/js/sidebar.js"></script>
<script src="/app-assets/custom/js/custom.js"></script>
@yield('custom-js')

resources/views/admin/layouts/sidebar.blade.php
<div class="main-menu menu-fixed menu-light menu-accordion menu-shadow" data-scroll-to-active="true">
    <div class="main-menu-content">
        <ul class="navigation navigation-main" id="main-menu-navigation" data-menu="menu-navigation">
            @canany(['view-project','project-modification','add-new-project','view-project-category','project-category-modification','add-new-project-category'])
            <li class="nav-item has-sub"><a href="#"><i class="ft-briefcase"></i><span class="menu-title" data-i18n="">Projects</span></a>
                <ul class="menu-content" style="">
                    @canany(['view-project','project-modification','add-new-project'])
                    <li class=""><a class="menu-item" href="{{ route('projects.index') }}">Projects</a>
                    </li>
                    @endcanany

                    @canany(['view-roproject-categoryle','project-category-modification','add-new-project-category'])
                    <li class=""><a class="menu-item" href="{{ route('projects.categories.index') }}">Categories</a>
                    </li>
                    @endcanany
                </ul>
            </li>
            @endcanany

            @canany(['view-news','news-modification','add-new-news'])
            <li class=" nav-item"><a href="{{ route('news.index') }}"><i class="ft-clipboard"></i><span class="menu-title" data-i18n="">News</span></a>
            </li>
            @endcanany

            @canany(['view-career','career-modification','add-new-career'])
                <li class=" nav-item"><a href="{{ route('careers.index') }}"><i class="ft-info"></i><span class="menu-title" data-i18n="">Careers</span></a>
                </li>
            @endcanany

            @canany(['banner-slider','our-story','video'])
            <li class=" nav-item"><a href="{{ route('homePage.index') }}"><i class="ft-home"></i><span class="menu-title" data-i18n="">Home Page</span></a>
            </li>
            @endcanany

            @canany(['management-team','company-profile','chairman-message'])
            <li class=" nav-item"><a href="{{ route('whoAreWe.index') }}"><i class="ft-help-circle"></i><span class="menu-title" data-i18n="">Who Are We</span></a>
            </li>
            @endcanany

            @canany(['contact-us-page'])
            <li class=" nav-item"><a href="{{ route('contactUs.index') }}"><i class="ft-phone"></i><span class="menu-title" data-i18n="">Contact Us</span></a>
            </li>
            @endcanany

            @canany(['about-us-page'])
            <li class=" nav-item"><a href="{{ route('aboutUs.index') }}"><i class="ft-info"></i><span class="menu-title" data-i18n="">About Us</span></a>
            </li>
            @endcanany

            @canany(['view-=page-image','page-image-modification'])
            <li class=" nav-item"><a href="{{ route('settings.page-image.index') }}"><i class="ft-info"></i><span class="menu-title" data-i18n="">Page Image</span></a>
            </li>
            @endcanany

            @canany(['view-social-media','social-media-modification'])
            <li class=" nav-item"><a href="{{ route('settings.social-media.index') }}"><i class="ft-info"></i><span class="menu-title" data-i18n="">Social Media</span></a>
            </li>
            @endcanany

            @canany(['view-seo','seo-modification'])
            <li class=" nav-item"><a href="{{ route('settings.seo.index') }}"><i class="ft-info"></i><span class="menu-title" data-i18n="">SEO</span></a>
            </li>
            @endcanany

            @canany(['view-user','user-modification','add-new-user','view-role','role-modification','add-new-role'])
            <li class="nav-item has-sub"><a href="#"><i class="ft-briefcase"></i><span class="menu-title" data-i18n="">Administrators</span></a>
                <ul class="menu-content" style="">
                    @canany(['view-user','user-modification','add-new-user'])
                    <li class=""><a class="menu-item" href="{{ route('users.index') }}">Users</a>
                    </li>
                    @endcanany

                    @canany(['view-role','role-modification','add-new-role'])
                    <li class=""><a class="menu-item" href="{{ route('roles.index') }}">Roles</a>
                    </li>
                    @endcanany
                </ul>
            </li>
            @endcanany
        </ul>
    </div>
</div>